name: Deep-RL-Hands-On
channels:
  - conda-forge
dependencies:
  - numpy
  - pandas
  - pip
  - python = 3.7
  - scikit-learn
  - scipy
  - seaborn
  - yaml
  - pyspark
  - pip: 
    - h5py
    - smopy
    - tensorflow
    - tensorboard-pytorch

